### PR TITLE
Turn ci.yml a callable workflow.

### PR DESCRIPTION
**Pull request by jvanz**
Updates the ci.yml adding the configuration to allow other workflows call it to run the tests.

### CODE REVIEW

**Review by ereslibre — APPROVED** [review]
Oops thanks!

**Review by viccuad — CHANGES_REQUESTED** [review]
I like the idea, but I'm not sure that reusing `make test` (the unit tests) is useful. In fact, they will run `make manifest`, etc. Is that what we want?

I would expect a new `make e2e-test`, that runs things similar to what there is right now in `e2e-tests/`.

**Comment by ereslibre** [comment]
> I would expect a new make e2e-test, that runs things similar to what there is right now in e2e-tests/.

Yes, I think we should run e2e-tests as well. I don't think there's anything wrong with running `make test` though, just an extra check that needs to pass before we call a release, besides the e2e-tests (that as said, I think we should add).

Thanks for realizing about that!

**Comment by viccuad** [comment]
Oh, from the conversation we had, I was thinking about reusing the workflow from the end-to-end-tests repo, not just reusing within this repo on the release workflow. Makes sense.

**Pull request merged**
