### PR TITLE
cluster admission policy: show bound policy server in table

### PR DESCRIPTION
**Pull request by ereslibre**

### CODE REVIEW

**Review by flavio — COMMENTED** [review]
LGTM, do you mind showing the new output?

**Comment by ereslibre** [comment]
Looks like this:

```
NAME                POLICY SERVER   MUTATING   STATUS
psp-capabilities    policyserver1   true       active
psp-capabilities2   policyserver2   true       active
psp-capabilities3   policyserver1   true       active
psp-capabilities4   policyserver2   true       active
psp-capabilities5   policyserver1   true       active
```

**Review by viccuad — APPROVED** [review]
Nice :)

**Review by raulcabello — APPROVED** [review]
great! :)

**Pull request merged**
