### PR TITLE
Add OpenSSF scorecard badge

### PR DESCRIPTION
**Pull request by raulcabello**

### CODE REVIEW

**Comment by raulcabello** [comment]
We want the best-practices badge not the scorecard, please don't review this PR yet

**Review by flavio — APPROVED** [review]
I think we can merge this PR, which I just converted from the draft status

**Comment by viccuad** [comment]
We already have the e2e tests badge, and the openssf best practices badge, I think this PR should be closed instead.

**Comment by raulcabello** [comment]
yes I agree with @viccuad. This PR was a leftover from the OpenSSF work
Closing it, feel free to reopen if you think we need this

**Pull request closed without merging**
