### PR TITLE
 Mutating field in the policy configmap

### PR DESCRIPTION
**Pull request by jvanz**
Adds a new field in the configmap where the policies info are store. The new "Mutating" field tells Policy Server that the policy can mutate requests or not.

### CODE REVIEW

**Review by flavio — CHANGES_REQUESTED** [review]
I would rename `mutating` to something different, like "disable_mutation" (see https://github.com/kubewarden/policy-server/pull/139)

**Review by viccuad — COMMENTED** [review]
Thanks for tackling this!

I wonder about the test, is it needed? The reconciler adds policies to the list regardless of their type, so we aren't testing here that they are added as validating or mutating by taking into account the new setting. To me it seems that the test should be in the end-to-end tests, and you have already added it with your work there.

**Comment by flavio** [comment]
This is related with https://github.com/kubewarden/allow-privilege-escalation-psp-policy/issues/9

**Comment by jvanz** [comment]
> Thanks for tackling this!
> 
> I wonder about the test, is it needed? The reconciler adds policies to the list regardless of their type, so we aren't testing here that they are added as validating or mutating by taking into account the new setting. To me it seems that the test should be in the end-to-end tests, and you have already added it with your work there.

I've added [tests](https://github.com/kubewarden/kubewarden-end-to-end-tests/pull/5) to validate the controller and policy server together. But I think we should use the Kubebuilder  [testing infrastructure](https://kubebuilder.io/cronjob-tutorial/writing-tests.html)  to validate the controller behavior alone. I`ll take a look on it to add something here as well.

**Review by flavio — APPROVED** [review]
LGTM

**Review by viccuad — APPROVED** [review]
Approving :) (my question was about `TestCreatePoliciesMap`, as I mistakenly didn't see the need for it, but please disregard it).

**Comment by jvanz** [comment]
> Approving :) (my question was about `TestCreatePoliciesMap`, as I mistakenly didn't see the need for it, but please disregard it).

Sorry, I've read your comment to fast the first times. Now I understand better what you said.

**Comment by viccuad** [comment]
No problem! I misunderstood the code in the test!

**Comment by viccuad** [comment]
Fixes https://github.com/kubewarden/policy-server/issues/137.

**Pull request merged**
