### PR TITLE
Bump to 1.19, refactor for `go.opentelemetry.io/otel/sdk` `0.32.1`

### PR DESCRIPTION
**Pull request by viccuad**
## Description

Supersedes https://github.com/kubewarden/kubewarden-controller/pull/214

- build: Bump to go 1.19
- Deps: bump dependencies, this includes go.opentelemetry.io/otel/sdk and related to 0.32.1
- refactor: Changes for go.opentelemetry.io/otel/sdk 0.32.1

## Test

To deploy Kubewarden with opentelemetry:

```shell
#!/usr/bin/env bash
set -ex

minikube addons enable ingress

# version at time of writing: cert-manager-v1.9.1
helm install --wait \
    --namespace cert-manager \
    --create-namespace \
    --set installCRDs=true \
    cert-manager jetstack/cert-manager

# version at time of writing:  opentelemetry-operator-0.13.0
helm install --wait \
  --namespace open-telemetry \
  --create-namespace \
  my-opentelemetry-operator open-telemetry/opentelemetry-operator

cat <<EOF > kube-prometheus-stack-values.yaml
prometheus:
  additionalServiceMonitors:
    - name: kubewarden
      selector:
        matchLabels:
          app: kubewarden-policy-server-default
      namespaceSelector:
        matchNames:
          - kubewarden
      endpoints:
        - port: metrics
          interval: 10s
EOF
# version at time of writing: kube-prometheus-stack-40.5.0
helm install --wait \
  --namespace prometheus \
  --create-namespace \
  --values kube-prometheus-stack-values.yaml \
  prometheus prometheus-community/kube-prometheus-stack

kubectl create namespace jaeger

# version at time of writing: jaeger-operator-2.36.0
helm upgrade -i --wait \
  --namespace jaeger \
  jaeger-operator jaegertracing/jaeger-operator \
  --set rbac.clusterRole=true

kubectl apply -f - <<EOF
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: my-open-telemetry
  namespace: jaeger
spec:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
EOF

helm install --wait \
  --namespace kubewarden \
  --create-namespace \
  kubewarden-crds kubewarden/kubewarden-crds

cat <<EOF > kubewarden-telemetry-values.yaml
telemetry:
  enabled: True
  metrics:
    port: 8080
  tracing:
    jaeger:
       endpoint: "my-open-telemetry-collector.jaeger.svc.cluster.local:14250"
    # this should be here to enable insecure endpoint. Needs to be added
    # by hand to the opentelemetrycollector resource, the helm chart will not honour it
    # tls:
     #  insecure: true
EOF
helm upgrade -i --wait \
  --namespace kubewarden \
  --create-namespace \
  --values kubewarden-telemetry-values.yaml \
  kubewarden-controller kubewarden/kubewarden-controller

# Now, edit the `opentelemetrycollector` created by the kubewarden-controller
# chart and enable tls.insecure
# Then, delete the controller Pod so it gets its sidecar

helm upgrade -i --wait \
  --namespace kubewarden \
  --create-namespace \
  kubewarden-defaults kubewarden/kubewarden-defaults \
  --set recommendedPolicies.enabled=True \
  --set recommendedPolicies.defaultPolicyMode=monitor \
  --set policyServer.telemetry.enabled=True
```

### CODE REVIEW

**Comment by viccuad** [comment]
I consider this ready for review.

I have failed to properly test open-telemetry for general availability charts, following the listed instructions above, though.

**Review by raulcabello — APPROVED** [review]
LGTM

**Comment by viccuad** [comment]
Thanks to @raulcabello, we have the instructions for deploying correctly the GA charts! Missing things were,
- `s/my-open-telemetry-collector/my-open-telemetry` in the metadata.name of the Jaeger resource
- enable rbac.clusterRole for the Jaeger chart
(edited the instructions)

**Comment by viccuad** [comment]
Built the controller image with this PR changes, one can apply it with:
```
  helm upgrade -i --wait \
    --namespace kubewarden \
    --create-namespace \
    --values kubewarden-telemetry-values.yaml \
    kubewarden-controller kubewarden/kubewarden-controller \
    --set image.repository=ghcr.io/viccuad/test/controller:bump-1.19

```

**Review by jvanz — APPROVED** [review]
LGTM. I can also run the stack locally using changes from this branch and see data in the jaeger and prometheus.

**Comment by flavio** [comment]
Great, rebase the PR and then merge it.

Do we need to update our docs explaining how to enable jaeger?

**Comment by viccuad** [comment]
We should update the docs, indeed.

We discovered also that after the controller refactor, we aren't publishing the `kubewarden_policy_total` metrics anymore. Let me have a quick look on where I can call the function to correctly update that metric.

**Comment by viccuad** [comment]
I don't see an easy way to re-introduce the `kubewarden_policy_total` metric. Moreover, I think it may be more useful to provide that metric per PolicyServer, not 1 for the whole cluster. I am punting on that, will rebase and merge as it is.

**Comment by viccuad** [comment]
Rebased. TODO:
- [ ]: Maybe change kubewarden-controller chart to accept setting `telemetry.tracer.jaeger.tls.insecure: true`
- [ ]: Update docs
- [ ]: Re-introduce `kubewarden_policy_total` metric, or others, into controller.

**Pull request merged**
