### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by ereslibre**

### CODE REVIEW

**Review by kkaempf — APPROVED** [review]
The "merge pull request" entries aren't useful and should rather list the PRs headline instead.

Approved for now, let's improve later.

**Review by flavio — APPROVED** [review]
I agree with what Klaus said. Can you file a new issue to fix that?

**Comment by ereslibre** [comment]
I will create the issue later and then merge.

**Comment by ereslibre** [comment]
Created https://github.com/kubewarden/kubewarden-controller/issues/30

**Pull request merged**
