### PR TITLE
deps: Bump dependencies for CVE fixes

### PR DESCRIPTION
**Pull request by viccuad**
## Description

Fix https://github.com/kubewarden/kubewarden-controller/issues/265

- deps: Bumped dependencies for CVE fixes, by running `go get -u && go tidy`.
- docs: Update and regenerate CRDs and CRDs docs.

## Test

Tested locally by building controller image and running latest `trivy` against it, report clean.

### CODE REVIEW

**Comment by viccuad** [comment]
Changelog already updated, once this hits main, we can do:
```
$ git tag -a v1.1.1  -m "v1.1.1" -s
$ git push upstream main v1.1.1
```

**Comment by viccuad** [comment]
Mh, failing to compile, lots of `module requires Go 1.19`. Here with `go1.18.5` it passed unit tests and built the image correctly. Will have a look.

**Comment by viccuad** [comment]
Bumped go to `1.18`, solved the issue. Will refrain to bump to `1.19` in this PR.

**Review by jvanz — APPROVED** [review]
LGTM! :D

**Comment by viccuad** [comment]
[e2e-tests passed!](https://github.com/kubewarden/kubewarden-controller/actions/runs/3105816310/jobs/5031930998)
Will cut a new release.

**Pull request merged**
