### PR TITLE
test: enable dependabot

### PR DESCRIPTION
**Pull request by flavio**
Configure dependabot to keep GH actions updated

### CODE REVIEW

**Review by viccuad — APPROVED** [review]

**Comment by viccuad** [comment]
Wait, renovate does detect github-actions, see https://github.com/kubewarden/kubewarden-controller/issues/159

**Review by viccuad — CHANGES_REQUESTED** [review]
Wait, renovate does detect github-actions, see: https://github.com/kubewarden/kubewarden-controller/issues/159

I think we just need to trigger it there in the dashboard. It would have happened weekly anyways.

**Comment by flavio** [comment]
Could it be that dependabot is the one that handles the nice `shasum # v1.2` syntax while renovate doesn't?

**Comment by viccuad** [comment]
That's it! For example, on sigstore-rs, we have the nice `shasum # v1.2` and it only has dependabot enabled.

I'm in for dealing with github-actions with dependabot, and disable renovatebot for them. For example with https://docs.renovatebot.com/configuration-options/#ignoredeps.

**Comment by viccuad** [comment]
Renovatebot seems to do the same, but maybe one needs to do it once for it to keep with it:
https://docs.renovatebot.com/modules/manager/github-actions/#additional-information

**Comment by flavio** [comment]
Nice finding! Then we could configure renovatebot to use the nice syntax it provides

**Comment by flavio** [comment]
Closing in favor of https://github.com/kubewarden/kubewarden-controller/pull/489

**Pull request closed without merging**
